### PR TITLE
Run DaskML example with Python 3.11 

### PR DESCRIPTION
**Pull request by nzw0301**
## Motivation

Run DaskML example with Python 3.11 for https://github.com/optuna/optuna-examples/issues/164.

## Description of the changes

Add python 3.11 to python-version matrix.

### CODE REVIEW

**Comment by toshihikoyanase** [comment]
Thank you for your PR. The CI worked as expected, but Python 3.11 support of dask-ml seems to be work-in-progress according to https://github.com/dask/dask-ml/issues/970.

**Comment by toshihikoyanase** [comment]
The DaskML members are still working on the support for Python 3.11, so let me reopen this PR.
https://github.com/dask/dask-ml/issues/970#issuecomment-1557320076

**Comment by not522** [comment]
@toshihikoyanase Could you continue the review as the assignee?

**Comment by toshihikoyanase** [comment]
@not522 Thanks for letting me know. The Dask-ml's official support for Python 3.11 may still take some time, but the features required by the Optuna example have already worked. So, let me introduce the change in this PR.

**Review by toshihikoyanase — APPROVED** [review]
LGTM. If the CI fails, we'll just roll back the change.

**Pull request merged**
