### PR TITLE
Add `LICENSE` file

### PR DESCRIPTION
**Pull request by not522**
## Motivation
Since optuna-examples is a split from Optuna, we need to put the same license file as the original.

## Description of the changes
- Add `LICENSE` file

### CODE REVIEW

**Comment by toshihikoyanase** [comment]
@Alnusjaponica Could you review this PR, please? As mentioned by the author, this repository should follow the MIT license like optuna/optuna. 
c.f., https://github.com/optuna/optuna/blob/b9a2fec629e27a6f97c74879f430265c83ec27b2/LICENSE#L1-L21

**Review by Alnusjaponica — APPROVED** [review]
I confirmed that the license sentence is exactly the same as `optuna/LICENSE`. LGTM.

**Comment by Alnusjaponica** [comment]
@toshihikoyanase Could you merge this PR?

**Comment by toshihikoyanase** [comment]
Thank you for your prompt action. I'll merge this PR.

**Pull request merged**
