### PR TITLE
Add `isort` to formatting checks

### PR DESCRIPTION
**Pull request by Crissman**
## Motivation

Main optuna/optuna repo uses `isort`, and it seems appropriate we should do the same for the examples.

## Description of the changes

- [x] Run `isort` to fix examples
- [x] Add to github checks action.
- [x] Add to CONTRIBUTING.md documentation

### CODE REVIEW

**Comment by Crissman** [comment]
Addresses #23

**Comment by Crissman** [comment]
@keisuke-umezawa Can you review this?

**Comment by keisuke-umezawa** [comment]
@Crissman 
You also need to modify `pyproject.toml`. 

https://github.com/optuna/optuna/blob/master/pyproject.toml#L20-L28

**Comment by Crissman** [comment]
@keisuke-umezawa `pyproject.toml` edited. PTAL, thanks.

**Review by keisuke-umezawa — APPROVED** [review]
LGTM! Thank you!

**Pull request merged**
