### PR TITLE
Add python 3.11 to ray's version matrix

### PR DESCRIPTION
**Pull request by nzw0301**
## Motivation

Resolve a sub-task of https://github.com/optuna/optuna-examples/issues/164.

## Description of the changes

As is the PR title.

### CODE REVIEW

**Comment by toshihikoyanase** [comment]
Thank you for your PR. The CI passed, but the [pypi of ray](https://pypi.org/project/ray/) does not list Python 3.11.
Do you check the example on Python 3.11?

image

**Comment by nzw0301** [comment]
No, I didn't check it. In fact, the latest stable ray supports Python 3.11 _experimentally_, so I'm not sure the example works without any errors...

**Comment by nzw0301** [comment]
I might take time to prepare for creating a python 3.11 environment for the local test, but I'll take a look at it.

**Comment by nzw0301** [comment]
Unfortunately, ray doesn't support macOS with python 3.11 yet, so I cannot test the example soon... 

Ref: https://docs.ray.io/en/latest/ray-overview/installation.html

**Comment by toshihikoyanase** [comment]
Thank you for your confirmation. I'll try it on WSL2.

**Comment by toshihikoyanase** [comment]
Sorry for the delayed response. Let me check this PR today.

**Review by toshihikoyanase — APPROVED** [review]
I confirmed that `joblib/ray_joblib.py` worked with Python 3.11 on a Linux machine.
LGTM!

```console
$ cd ray
$ pip install oputna scikit-learn ray
$ python ray_joblib.py
...
Number of finished trials: 100
Elapsed time: 0:05:28.487118
Best trial:
  Value: 0.9866666666666667
  Params:
    classifier: SVC
    svc_c: 4.216210865309544
```

During the review, I'm wondering the following things:
- Why the CI workflow does not execute the example. It easily worked like the other examples in my environment.
- Why `requirements.txt` lacks in this directory

Maybe we can work on them in follow-up PRs.

**Pull request merged**
