### PR TITLE
Install `optuna-integration` on all integration examples

### PR DESCRIPTION
**Pull request by HideakiImamura**
## Motivation

To pass the CI including future migration of integration libraries in Optuna.

## Description of the changes

Install `optuna-integration` on all integration examples.

### CODE REVIEW

**Comment by HideakiImamura** [comment]
@gen740 Could you review this PR?

**Review by gen740 — COMMENTED** [review]
Just as `samplers` and `visualization` do not have `optuna_integration` installed, I believe there is no need to install `optuna_integration` for examples that do not depend on Optuna integration, such as `hiplot` and `multi_objective`.

**Comment by HideakiImamura** [comment]
@gen740 I revert some changes as you suggested. PTAL.

**Review by gen740 — APPROVED** [review]
LGTM!

**Pull request merged**
