### PR TITLE
Make Keras examples Keras 3 friendly.

### PR DESCRIPTION
**Pull request by nzw0301**
## Motivation

Similar to https://github.com/optuna/optuna-integration/issues/91.

## Description of the changes

- Remove deprecated warning messages
- Replace tf.keras with keras
- Use Input class to remove warning message by Keras 3.0

I confirmed the examples work fine with Keras 3.0 and jax/pytorch.

### CODE REVIEW

**Comment by nzw0301** [comment]
Please let me know if I should apply similar changes to [mlflow w/ keras example](https://github.com/optuna/optuna-examples/blob/main/mlflow/keras_mlflow.py).

**Review by y0z — APPROVED** [review]
Thank you for your contribution.
LGTM.

> Please let me know if I should apply similar changes to [mlflow w/ keras example](https://github.com/optuna/optuna-examples/blob/main/mlflow/keras_mlflow.py).

Yes please. We will update the version of Keras to the version 3.

**Comment by nzw0301** [comment]
Sure. I'll send another PR in a week.

**Comment by HideakiImamura** [comment]
Let me merge this PR since we had one approval.

**Review by HideakiImamura — APPROVED** [review]

**Pull request merged**
