### PR TITLE
Add `OptunaSearchCV` with terminator

### PR DESCRIPTION
**Pull request by Alnusjaponica**
## Motivation
Thanks to https://github.com/optuna/optuna/pull/5098, now we can use terminator in `OptunaSearchCV`.  This example shows how to use it.

## Description of the changes
The example itself is basically the same as `sklearn/sklearn_optuna_search_cv_simple.py` except that `TerminatorCallback` with default setting is passed to `OptunaSearchCV`.
I added the example under `terminator/` so that we don't have to change dependency of each module.

### CODE REVIEW

**Comment by c-bata** [comment]
@nabenabe0928 Could you review this PR?

**Comment by c-bata** [comment]
@Alnusjaponica Could you update README.md to add a link?
https://github.com/optuna/optuna-examples#examples-of-terminator

**Comment by nabenabe0928** [comment]
> @nabenabe0928 Could you review this PR?

Yes

**Comment by Alnusjaponica** [comment]
@c-bata I updated `README.md`. PTAL.

**Comment by c-bata** [comment]
@Alnusjaponica Thank you for the update!

@nabenabe0928 Could you please let me know once you approve? I'll then merge this PR.

**Review by nabenabe0928 — APPROVED** [review]
Thank you for the PR, LGTM!

**Review by HideakiImamura — APPROVED** [review]

**Pull request merged**
