### PR TITLE
Use `MLflowCallback` in mlflow example

### LINKED ISSUE #56: Add `MLflowCallback` example
## Motivation

This repo does not provide a minimal example of [`MLflowCallback`](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.integration.MLflowCallback.html). There exist two MLflow examples as follows:

- [`mlflow/keras_mlflow.py`](https://github.com/optuna/optuna-examples/blob/e68e86d5c7fd91727da869d9708a770757150da9/mlflow/keras_mlflow.py): using pure MLflow, not `MLflowCallback`.
- [`kubernetes/mlflow/pytorch_lightning_distributed.py`](https://github.com/optuna/optuna-examples/blob/6a6b20ad634627eebb3e7e104f73b70b45c6e624/kubernetes/mlflow/pytorch_lightning_distributed.py): using `MLflowCallback`, but it looks complicated.

I think it would be great to provide such a minimal example.

## Description

Please add mlflow callback example similar way to https://github.com/optuna/optuna-examples/issues/41.

### PR DESCRIPTION
**Pull request by xadrianzetx**
## Motivation

Previous simple example did not use existing  `MLflowCallback` integration, and opted for raw mlflow instead. Now, example shows intended way to use Optuna with mlflow.

Resolves #56. This is a PR with limited scope created after discussion in #57.

## Description of the changes

* Use `MLflowCallback` in mlflow example
* Rename mlflow example to follow naming convention

### CODE REVIEW

**Comment by xadrianzetx** [comment]
Friendly ping, @nzw0301 :^)
If breaking changes introduced by renaming the example are in conflict with repo policy, i will revert them.

**Comment by nzw0301** [comment]
Awesome! 

Sorry for the delayed response. Some members, workers in Japan except for at least me, enjoy holidays until the beginning of the next ### week. So please give us a time little bit to decide how to deal with this PR.

**Comment by nzw0301** [comment]
[sidenote]
If we can rename mlflow's example file name as is this PR,
we might need to replace MLflow's link on [`REAEDME`(https://github.com/optuna/optuna-examples/blob/main/README.md) and [this line](https://github.com/optuna/optuna-examples/blob/4b26669c703806227b915357ba2815ef3f6be54f/keras/keras_integration.py#L14).

**Comment by nzw0301** [comment]
@xadrianzetx Hi, sorry for the delayed response again.

When I talked with @toshihikoyanase, 

- we would like to keep the file name `mlflow_simple.py`.
- the suggested change in `mlflow_simple.py` is perfect.

So could you undo the renaming commit?

**Comment by xadrianzetx** [comment]
> we would like to keep the file name mlflow_simple.py.
> So could you undo the renaming commit?

Just to be clear, we are going back from `mlflow_simple.py` to `keras_mlflow.py`?

**Comment by nzw0301** [comment]
@xadrianzetx Sorry for my unclear comment. Yes, you're right.

**Comment by nzw0301** [comment]
Indeed, [my comment](https://github.com/optuna/optuna-examples/pull/58#issuecomment-926534166) was wrong; I updated it. Sorry for confusing you...

**Comment by xadrianzetx** [comment]
Thank you for the opinions, guys. Please consider squash merging, as commit history looks weird.

**Review by nzw0301 — APPROVED** [review]
LGTM! Thanks.

**Pull request merged**
