### PR TITLE
Remove constraint of `setuptools`

### PR DESCRIPTION
**Pull request by nzw0301**
## Motivation

New `setuptools` has been released.

## Description of the changes

Revert https://github.com/optuna/optuna-examples/pull/76

### CODE REVIEW

**Comment by nzw0301** [comment]
I'm not sure why the following error happens in the CI.

```bash
Run python pytorch/pytorch_lightning_simple.py
Traceback (most recent call last):
  File "pytorch/pytorch_lightning_simple.py", line 19, in <module>
    from optuna.integration import PyTorchLightningPruningCallback
ImportError: cannot import name 'PyTorchLightningPruningCallback'
Error: Process completed with exit code 1.
```

Note that we're seeing the same s error the last few days...

**Comment by hvy** [comment]
Changes LGTM. Although likely not related to this change, do you know how the above error was fixed?

**Comment by nzw0301** [comment]
Thank you for your review! 

Honestly, I don't know. The error did hot happen today, https://github.com/optuna/optuna-examples/actions/runs/173622026.

**Review by hvy — APPROVED** [review]
LGTM!

**Pull request merged**
