### PR TITLE
Update SimulatedAnnealingSampler to support FloatDistribution

### PR DESCRIPTION
**Pull request by himkt**
🔗 https://github.com/optuna/optuna/pull/3246

## Motivation
This PR updates SimulatedAnnealingSampler to support `FloatDistribution`.

### CODE REVIEW

**Comment by nzw0301** [comment]
Nice. How about replacing https://github.com/optuna/optuna-examples/blob/281b6b63d495e64625957b9dcfab6dade19c3741/samplers/simulated_annealing_sampler.py#L8 with `uniform distribution` because `UniformDistribution` will have been deprecated since v3.0.0.

**Comment by himkt** [comment]
You're absolutely right, thank you. Updated in [6796da2](https://github.com/optuna/optuna-examples/pull/97/commits/6796da247675a0ac299e51bb117826380fe3f22e).

**Comment by nzw0301** [comment]
Well, `FloatDistribution ` is not accurate yet because some cases, such as `FloatDistribution(low, high, log=True)`, are also invalid in this example. This is why I suggested `uniform distribution` in the previous comment. If we prefer to use a distribution class, `FloatDistribution(low, high, step=None, log=False)` is supposed to be the most accurate.

**Comment by himkt** [comment]
Hmm, thank you for the feedback. So you mean "i.e., `Trial.suggest_float(low, high, step=None, log=False)`" is still ambiguous, right? I think `uniform distribution` is also confusing since distributions in Optuna are uniform in its domains...

**Comment by himkt** [comment]
Does adding a note like `SimulatedAnnealingSampler doesn't work with logarithmic domain or discretized distribution` make sense?

**Comment by nzw0301** [comment]
Maybe, 

```
- The sampler only supports `Trial.suggest_float(low, high, step=None, log=False)` method.
```
looks enough.

**Comment by himkt** [comment]
Sounds perfect. Thank you!

**Review by nzw0301 — APPROVED** [review]
Thanks

**Comment by himkt** [comment]
Thank you for the fast iterating!

**Pull request merged**
