### PR TITLE
Add NCCL support for `pytorch_distributed_simple.py`

### PR DESCRIPTION
**Pull request by toshihikoyanase**
## Motivation

Alternative approach for https://github.com/optuna/optuna-examples/pull/145.

## Description of the changes

- Use `device` argument of `optuna.integration.TorchDistributedTrial`
- Check local rank to specify CUDA device in a node
- Use `MASTER_ADDR` and `MASTER_PORT` in environment variables if exist

I confirmed that this script worked with 2 nodes.

```console
$ mpiexec -x OMP_NUM_THREADS=1 --bind-to none \
    -x MASTER_ADDR="your master address" \
    -x MASTER_PORT="your master port" \
    python pytorch/pytorch_distributed_simple.py
```

See
https://pytorch.org/docs/stable/distributed.html

### CODE REVIEW

**Comment by HideakiImamura** [comment]
@not522 Could you review this PR?

**Comment by toshihikoyanase** [comment]
I found that this code does not work on the PC which has NVIDIA GPUs without NCCL support.
If you have any idea to check NCCL availability, please let me know.

**Comment by not522** [comment]
Sorry for my late response. I have been busy these days and don't have time to review this PR, so could you please reassign the reviewer?

**Comment by c-bata** [comment]
I will review this PR along with https://github.com/optuna/optuna/pull/4268. @toshihikoyanase Could you fix CI errors?

**Comment by toshihikoyanase** [comment]
Let me close this PR since it uses the old API. I'll create a new one.

**Pull request closed without merging**
